driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
    driver_config:
      box: bento/centos-6.7
  - name: centos-7.1
    driver_config:
      box: bento/centos-7.1

suites:
  - name: default
    run_list:
      - recipe[yum-oracle::default]
